In [133]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.datasets import load_wine
from sklearn.model_selection import  train_test_split
from sklearn.model_selection import StratifiedKFold, cross_val_score


In [75]:
wine_dataset = load_wine()
cols = [j for i, j in enumerate(wine_dataset['feature_names']) if (i==9 or i==11 or i==12) ]
cols
X, y = pd.DataFrame(wine_dataset['data'], 
                    columns = wine_dataset['feature_names']), wine_dataset['target']

In [76]:
for i in wine_dataset['feature_names']:
    if i not in cols:
        del X[i]
X

color_intensity  od280/od315_of_diluted_wines  proline
0               5.64                          3.92   1065.0
1               4.38                          3.40   1050.0
2               5.68                          3.17   1185.0
3               7.80                          3.45   1480.0
4               4.32                          2.93    735.0
..               ...                           ...      ...
173             7.70                          1.74    740.0
174             7.30                          1.56    750.0
175            10.20                          1.56    835.0
176             9.30                          1.62    840.0
177             9.20                          1.60    560.0

[178 rows x 3 columns]

In [77]:
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=.2,
                                                    random_state=17)

In [84]:
skf = StratifiedKFold(n_splits=5, random_state=17)
skf

StratifiedKFold(n_splits=5, random_state=17, shuffle=False)

In [96]:
log_reg = LogisticRegression(random_state=17)
log_reg_model = log_reg.fit(X_train, y_train)
cross_val_score(log_reg, X, y, cv=skf)

C:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_ms

array([0.91666667, 0.75      , 0.91666667, 0.94285714, 0.97142857])

In [115]:
np.mean(np.array(cross_val_score(log_reg, X, y, cv=skf)))

C:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_ms

0.8995238095238095

In [140]:
log_reg_pred = log_reg.predict(X_test)
accuracy = accuracy_score(y_test, log_reg_pred)
accuracy

1.0

In [122]:
from sklearn.svm import SVC

In [146]:
svm_model = SVC(random_state=17).fit(X_train, y_train)
cross_val_score(svm_model, X, y, cv=skf)

array([0.63888889, 0.63888889, 0.63888889, 0.74285714, 0.74285714])

In [154]:
svm_pred = svm_model.predict(X_test)
accuracy = accuracy_score(y_test, svc_pred)
accuracy
confusion_matrix(y_test, svm_pred)

array([[ 8,  0,  0],
       [ 0, 16,  0],
       [ 1, 11,  0]], dtype=int64)

In [158]:
# for Logistic Regression
print(classification_report(y_test, log_reg_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00        12

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36



In [157]:
# for SVM
print(classification_report(y_test, svm_pred))

              precision    recall  f1-score   support

           0       0.89      1.00      0.94         8
           1       0.59      1.00      0.74        16
           2       0.00      0.00      0.00        12

    accuracy                           0.67        36
   macro avg       0.49      0.67      0.56        36
weighted avg       0.46      0.67      0.54        36

